new func to add agencies
derhuerst/hafas-generate-gtfs pull request #2
Opened 2020-04-29 12:27 UTC by asuender

I've added a function to add all appearing agencies and made some changes at `collectDepsAt()` and `addLine()`.

2020-05-16 18:22 UTC, derhuerst requested changes
Thanks for your contribution and sorry for taking so long to respond! I have some minor change requests.

2020-05-16 18:22 UTC, derhuerst commented on index.js
> +				if (!agencies.has(dep.line.operator.name))
Please use `dep.line.operator.id` as the key in `agencies`.

2020-05-16 18:22 UTC, derhuerst commented on index.js
> +			// leave this temporary blank, see e.g.
Please keep the todo here. Referencing the `agency.txt` entry from the `routes.txt` entry still needs to be done.

2020-06-04 13:32 UTC, derhuerst commented
@asuender ping 😉

2020-06-04 16:16 UTC, asuender commented
Sorry I hadn‘t much time to fix this, I gonna do this soon. Sorry again.

2020-06-23 23:46 UTC, derhuerst commented
@asuender another ping. if you don‘t have time, that‘s fine obviously

2020-07-24 09:42 UTC, merged

2020-07-24 09:42 UTC, derhuerst commented
Thanks!